### ISSUE TITLE
Error while testing the detector

### ISSUE THREAD

**Issue by abdelrahman-gaber** [louis-she/sfd.pytorch#23]
Hi, thank you for the great work. 
I was trying to test your code, but when I run:
python3 detector.py --image ./images/test.jpg --model ./epoch_41.pth.tar
I got the following error.
```
predicted bounding boxes of faces:
Traceback (most recent call last):
  File "detector.py", line 160, in <module>
    main(args)
  File "detector.py", line 141, in main
    bboxes = Detector(args.model).infer(args.image)
  File "detector.py", line 24, in __init__
    self.model.load_state_dict(checkpoint['state_dict'], strict=True)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Net:
	Missing key(s) in state_dict: "predict3_3_reg.weight", "predict3_3_reg.bias", "predict4_3_reg.weight", "predict4_3_reg.bias", "predict5_3_reg.weight", "predict5_3_reg.bias", "predict_fc7_reg.weight", "predict_fc7_reg.bias", "predict6_2_reg.weight", "predict6_2_reg.bias", "predict7_2_reg.weight", "predict7_2_reg.bias", "predict3_3_cls.weight", "predict3_3_cls.bias", "predict4_3_cls.weight", "predict4_3_cls.bias", "predict5_3_cls.weight", "predict5_3_cls.bias", "predict_fc7_cls.weight", "predict_fc7_cls.bias", "predict6_2_cls.weight", "predict6_2_cls.bias", "predict7_2_cls.weight", "predict7_2_cls.bias". 
	Unexpected key(s) in state_dict: "predict3_3.weight", "predict3_3.bias", "predict4_3.weight", "predict4_3.bias", "predict5_3.weight", "predict5_3.bias", "predict_fc7.weight", "predict_fc7.bias", "predict6_2.weight", "predict6_2.bias", "predict7_2.weight", "predict7_2.bias". 
```

It seems to be something wrong in the provided model or the way to read the model, but I am new to pytorch and couldn't figure out the problem. I have pytorch 0.4 and python 3.6 as required.

Thank you.

**Comment by queryor** [comment]
@abdelrahman-gaber have you solve this problem. I have this problem too.

**Comment by One-way-Leon** [comment]
@abdelrahman-gaber I met this problem too. which the model did you download ? I download the model from BaiduDriver.  The model have some little problems when I debug this py. when i use the model which was trained by myself, it's ok. so i suggest that  you don't use the provided model.  Train one yourself.

**Comment by louis-she** [comment]
Sorry for the very late response, but the error has been fixed.
