### ISSUE TITLE
import error：cannot import name 'cfg'

### ISSUE THREAD

**Issue by JCBourne97** [louis-she/sfd.pytorch#39]
Then I run the command:
python3 detector.py --image ./image/test.jpg --model ./epoch_204.pth.tar
Then I got this error:
Traceback (most recent call last):
  File "detector.py", line 11, in <module>
    from model import Net
  File "E:\code\S3FD\sfd.pytorch-master\model.py", line 5, in <module>
    from torchvision.models.vgg import VGG, cfg, make_layers, vgg16
ImportError: cannot import name 'cfg'
And I still don't figure out what goes wrong

**Comment by Aliumutcan** [comment]
i changed cfg to cfgs for solution
